/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageLayerProps.java
 *
 * Created on 17.5.2009, 21:21:37
 */

package lilay;

/**
 *
 * @author root
 */
public class LayerPropertiesDialog extends javax.swing.JDialog
{
    Layer layer;

    public LayerPropertiesDialog( java.awt.Frame parent, int layerId )
    {
        super( parent, true );
        initComponents();

        layer = Core.instance.layers.elementAt( layerId );
        layerName.setText( layer.name );

        switch ( layer.type )
        {
            case Layer.Layer_image:
                imageSource.setText( layer.imageSource.toString() );
                xSpinner.setValue( layer.pos.x );
                ySpinner.setValue( layer.pos.y );
                opacitySpinner.setValue( layer.opacity );

                tabPane.setSelectedComponent( imagePanel );
                break;

            case Layer.Layer_tileset:
                tilesetSource.setText( layer.imageSource.toString() );
                tileWSpinner.setValue( layer.tileSize.width );
                tileHSpinner.setValue( layer.tileSize.height );

                tabPane.setSelectedComponent( tilesetPanel );
                break;

            case Layer.Layer_collision:
                tileWSpinnerC.setValue( layer.tileSize.width );
                tileHSpinnerC.setValue( layer.tileSize.height );

                tabPane.setSelectedComponent( collisionMapPanel );
                break;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        layerName = new javax.swing.JTextField();
        buttonSave = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        imagePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imageSource = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        xSpinner = new javax.swing.JSpinner();
        ySpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        opacitySpinner = new javax.swing.JSpinner();
        tilesetPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tilesetSource = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tileWSpinner = new javax.swing.JSpinner();
        tileHSpinner = new javax.swing.JSpinner();
        collisionMapPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tileWSpinnerC = new javax.swing.JSpinner();
        tileHSpinnerC = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lilay.LilayEditorApp.class).getContext().getResourceMap(LayerPropertiesDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel1.setText(resourceMap.getString("layerNameText")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        layerName.setFont(resourceMap.getFont("uiFont")); // NOI18N
        layerName.setName("layerName"); // NOI18N

        buttonSave.setFont(resourceMap.getFont("uiFont")); // NOI18N
        buttonSave.setText(resourceMap.getString("saveButtonText")); // NOI18N
        buttonSave.setName("buttonSave"); // NOI18N
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonClose.setFont(resourceMap.getFont("uiFont")); // NOI18N
        buttonClose.setText(resourceMap.getString("cancelButtonText")); // NOI18N
        buttonClose.setName("buttonClose"); // NOI18N
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        tabPane.setFont(resourceMap.getFont("uiFont")); // NOI18N
        tabPane.setName("tabPane"); // NOI18N

        imagePanel.setFont(resourceMap.getFont("uiFont")); // NOI18N
        imagePanel.setName("imagePanel"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel2.setText(resourceMap.getString("imageSourceText")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        imageSource.setFont(resourceMap.getFont("uiFont")); // NOI18N
        imageSource.setName("imageSource"); // NOI18N

        jLabel3.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        xSpinner.setFont(resourceMap.getFont("uiFont")); // NOI18N
        xSpinner.setName("xSpinner"); // NOI18N

        ySpinner.setFont(resourceMap.getFont("uiFont")); // NOI18N
        ySpinner.setName("ySpinner"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        opacitySpinner.setFont(resourceMap.getFont("uiFont")); // NOI18N
        opacitySpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), Float.valueOf(1.0f), Float.valueOf(0.1f)));
        opacitySpinner.setName("opacitySpinner"); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageSource, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(xSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(opacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(imageSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(xSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabPane.addTab(resourceMap.getString("imagePanel.TabConstraints.tabTitle"), imagePanel); // NOI18N

        tilesetPanel.setFont(resourceMap.getFont("tilesetPanel.font")); // NOI18N
        tilesetPanel.setName("tilesetPanel"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        tilesetSource.setFont(resourceMap.getFont("uiFont")); // NOI18N
        tilesetSource.setName("tilesetSource"); // NOI18N

        jLabel5.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        tileWSpinner.setFont(resourceMap.getFont("uiFont")); // NOI18N
        tileWSpinner.setName("tileWSpinner"); // NOI18N

        tileHSpinner.setFont(resourceMap.getFont("uiFont")); // NOI18N
        tileHSpinner.setName("tileHSpinner"); // NOI18N

        javax.swing.GroupLayout tilesetPanelLayout = new javax.swing.GroupLayout(tilesetPanel);
        tilesetPanel.setLayout(tilesetPanelLayout);
        tilesetPanelLayout.setHorizontalGroup(
            tilesetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilesetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tilesetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tilesetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tilesetSource, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(tilesetPanelLayout.createSequentialGroup()
                        .addComponent(tileWSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tileHSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tilesetPanelLayout.setVerticalGroup(
            tilesetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tilesetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tilesetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tilesetSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tilesetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tileWSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tileHSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tabPane.addTab(resourceMap.getString("tilesetPanel.TabConstraints.tabTitle"), tilesetPanel); // NOI18N

        collisionMapPanel.setFont(resourceMap.getFont("collisionMapPanel.font")); // NOI18N
        collisionMapPanel.setName("collisionMapPanel"); // NOI18N

        jLabel8.setFont(resourceMap.getFont("uiFont")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        tileWSpinnerC.setFont(resourceMap.getFont("uiFont")); // NOI18N
        tileWSpinnerC.setName("tileWSpinnerC"); // NOI18N

        tileHSpinnerC.setFont(resourceMap.getFont("uiFont")); // NOI18N
        tileHSpinnerC.setName("tileHSpinnerC"); // NOI18N

        javax.swing.GroupLayout collisionMapPanelLayout = new javax.swing.GroupLayout(collisionMapPanel);
        collisionMapPanel.setLayout(collisionMapPanelLayout);
        collisionMapPanelLayout.setHorizontalGroup(
            collisionMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collisionMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(tileWSpinnerC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tileHSpinnerC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        collisionMapPanelLayout.setVerticalGroup(
            collisionMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(collisionMapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collisionMapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tileWSpinnerC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tileHSpinnerC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tabPane.addTab(resourceMap.getString("collisionMapPanel.TabConstraints.tabTitle"), collisionMapPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(layerName, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addComponent(buttonClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(layerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonClose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        layer.name = layerName.getText();
        switch ( layer.type )
        {
            case Layer.Layer_image:
                layer.imageSource.set( imageSource.getText() );
                layer.pos.setLocation( ( Integer )xSpinner.getValue(),
                        ( Integer )ySpinner.getValue() );
                layer.opacity = ( Float )opacitySpinner.getValue();
                break;

            case Layer.Layer_tileset:
                layer.imageSource.set( tilesetSource.getText() );
                layer.setTileSize( ( Integer )tileWSpinner.getValue(),
                        ( Integer )tileHSpinner.getValue() );
                break;

            case Layer.Layer_collision:
                layer.setTileSize( ( Integer )tileWSpinnerC.getValue(),
                        ( Integer )tileHSpinnerC.getValue() );
                break;
        }

        dispose();
}//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        dispose();
}//GEN-LAST:event_buttonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonSave;
    private javax.swing.JPanel collisionMapPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JTextField imageSource;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField layerName;
    private javax.swing.JSpinner opacitySpinner;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JSpinner tileHSpinner;
    private javax.swing.JSpinner tileHSpinnerC;
    private javax.swing.JSpinner tileWSpinner;
    private javax.swing.JSpinner tileWSpinnerC;
    private javax.swing.JPanel tilesetPanel;
    private javax.swing.JTextField tilesetSource;
    private javax.swing.JSpinner xSpinner;
    private javax.swing.JSpinner ySpinner;
    // End of variables declaration//GEN-END:variables

}
