
/*
 * EditorCanvas.java
 *
 * Created on 16.5.2009, 13:46:33
 */

package lilay;

import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Minexewl
 */
public class TileChooserCanvas extends javax.swing.JPanel
{
    static TileChooserCanvas instance;
    Layer layer;

    public TileChooserCanvas( Layer layer )
    {
        setPreferredSize( new Dimension( layer.imageSource.width, layer.imageSource.height ) );
        initComponents();

        ( instance = this ).layer = layer;

        addMouseListener( new MouseAdapter()
        {
            @Override public void mouseClicked( MouseEvent event )
            {
                instance.layer.selectTile( event.getX(), event.getY() );
                instance.repaint();
            }
        } );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(100, 100));
        setName("Form"); // NOI18N
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override protected void paintComponent( Graphics g )
    {
        super.paintComponent( g );

        layer.paintTileset( ( Graphics2D )g, this );
    }
}
